print("This is the given text:")
print("Today I went to a {adjective1} zoo")
print("In an exhibit, I saw a {noun}")
print("{noun} was {adjective2} and {verb}ing")
print("I was {adjective3}\n")

adjective1 = input("Enter an adjective1: ")
noun = input("Enter a noun: ")
adjective2 = input("Enter an adjective2: ")
verb = input("Enter a verb: ")
adjective3 = input("Enter an adjective3: ")

print(f"Today I went to a {adjective1} zoo")
print(f"In an exhibit, I saw {noun}")
print(f"{noun} was an {adjective2} and {verb}ing")
print(f"I was {adjective3}")
